# Generated by Django 5.0.6 on 2024-09-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('temperature', models.CharField(blank=True, max_length=200, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
